#pragma once
#include <string>
#include <unordered_map>

namespace Language
{
    inline bool IsPortuguese = false;

    inline std::unordered_map<std::string, std::string> Translations = {
        {"Enabled", "Ativado"},
        {"Disabled", "Desativado"},
        {"Save", "Salvar"},
        {"Close", "Fechar"},
        {"Search", "Pesquisar"},
        {"Login", "Entrar"},
        {"Language", "Idioma"},

        {"Combat", "Combate"},
        {"Visuals", "Visuais"},
        {"Exploits", "Exploracoes"},
        {"World", "Mundo"},
        {"Settings", "Configuracoes"},
        {"General", "Geral"},
        {"Trolls", "Trolls"},
        {"Aimbot", "Mira"},
        {"Silent", "Silenciosa"},
        {"Silent Aim", "Mira Silenciosa"},
        {"Trigger", "Gatilho"},
        {"Trigger Bot", "Gatilho Automatico"},
        {"Player", "Jogador"},
        {"Players", "Jogadores"},
        {"Weapons", "Armas"},
        {"Vehicles", "Veiculos"},
        {"Colors", "Cores"},
        {"Teleport", "Teleporte"},
        {"Configs", "Configuracoes"},

        {"Box", "Caixa"},


        {"Skeleton", "Esqueleto"},
        {"Name", "Nome"},
        {"Player Names", "Nomes dos Jogadores"},
        {"Weapon Names", "Nomes das Armas"},
        {"Head Circle", "Circulo na Cabeca"},
        {"Health Bar", "Barra de Vida"},
        {"Armor Bar", "Barra de Armadura"},
        {"Distance", "Distancia"},
        {"Weapon", "Arma"},
        {"Weapon Name", "Nome da Arma"},
        {"SnapLines", "Linhas de Mira"},
        {"Font Type", "Tipo de Fonte"},
        {"Font Weight", "Espessura da Fonte"},
        {"Box Type", "Tipo de Caixa"},
        {"RGB", "RGB"},
        {"RGB Speed", "Velocidade RGB"},
        {"Show LocalPlayer", "Mostrar LocalPlayer"},
        {"Ignore Dead", "Ignorar Mortos"},
        {"Ignore Invisible", "Ignorar Invisiveis"},
        {"Friend Marker", "Marcar Amigo"},

        {"Toggle", "Ativar"},
        {"Enable Aim Assist", "Ativar Assistencia de Mira"},
        {"Show Fov", "Mostrar Campo"},
        {"Dynamic Fov", "Campo Dinamico"},
        {"Legit Mode", "Modo Legitimo"},
        {"Field of View", "Campo de Visao"},
        {"Smooth", "Suavidade"},
        {"Max Distance", "Distancia Maxima"},
        {"Only Visible", "Apenas Visivel"},
        {"Ignore NPCs", "Ignorar NPCs"},
        {"HitBox", "Area de Acerto"},
        {"Head", "Cabeca"},
        {"Neck", "Pescoco"},
        {"Chest", "Peito"},
        {"Pelvis", "Pelve"},
        {"Prediction", "Previsao"},
        {"Miss Chance", "Chance de Erro"},
        {"Smart Triggerbot", "Triggerbot Inteligente"},
        {"Delay", "Atraso"},
        {"Bind", "Atalho"},
        {"Magic Bullets", "Balas Magicas"},

        {"God Mode", "Modo Deus"},
        {"GodMode", "Modo Deus"},
        {"Noclip", "Atravessar Paredes"},
        {"NoClip", "Atravessar Paredes"},
        {"Invisible", "Invisivel"},
        {"Infinite Ammo", "Municao Infinita"},
        {"No Recoil", "Sem Recuo"},
        {"No Spread", "Sem Dispersao"},
        {"Weapon Scale", "Escala da Arma"},
        {"Weapon Scale Value", "Valor da Escala"},
        {"Fast Run", "Correr Rapido"},
        {"Super Jump", "Super Pul"},
        {"Shrink", "Virar Anao"},
        {"Anti-Aim", "Anti-Aim"},
        {"Anti-Aim Key", "Tecla Anti-Aim"},
        {"Infinite Stamina", "Estamina Infinita"},
        {"Infinite Combat Roll", "Rolagem Infinita"},
        {"No Fall Damage", "Sem Dano de Queda"},
        {"Steal Car", "Roubar Carro"},
        {"FreeCam", "Camera Livre"},
        {"No Collision", "Sem Colisao"},

        {"No Reload", "Sem Recarregar"},
        {"Suicide", "Suicidio"},
        {"Full Health", "Vida Cheia"},
        {"Full Armor", "Colete Cheio"},
        {"Full Stamina", "Estamina Cheia"},
        {"Revive", "Reviver"},

        {"Vehicle Names", "Nomes dos Veiculos"},
        {"Vehicle GodMode", "Modo Deus Veiculo"},
        {"Locked/Unlocked", "Trancado/Destrancado"},
        {"Repair Vehicle", "Consertar Veiculo"},
        {"Seat Belt", "Cinto de Seguranca"},
        {"Rocket Boost", "Foguete"},
        {"Boost Strength", "Forca do Boost"},
        {"Fix Vehicle", "Consertar Veiculo"},
        {"Vehicle Color", "Cor do Veiculo"},

        {"Export Config", "Exportar Config"},
        {"Import Config", "Importar Config"},
        {"Save to File", "Salvar em Arquivo"},
        {"Load from File", "Carregar Arquivo"},
        {"Menu Key", "Tecla do Menu"},
        {"Unload", "Descarregar"},
        {"Stream Mode", "Modo Stream"},
        {"Safe Mode", "Modo Seguro"},
        {"Active Features", "Recursos Ativos"},
        {"Watermark", "Marca d Agua"},
        {"Watermark Color", "Cor da Marca"},
        {"Particles", "Particulas"},
        {"Second Monitor", "Segundo Monitor"},
        {"Web Remote", "Web Remoto"},
        {"Account Information", "Informacoes da Conta"},
        {"Resources", "Recursos"},
        {"No resources found", "Nenhum recurso encontrado"},

        {"Add Friend", "Adicionar Amigo"},
        {"Unfriend", "Remover Amigo"},
        {"Teleport to Player", "Teleportar para Jogador"},
        {"Teleport to Waypoint", "Teleportar para Marco"},
        {"Teleport to Location", "Teleportar para Local"},
        {"Copy Clothes", "Copiar Roupas"},
        {"Clone Vehicle", "Clonar Veiculo"},

        {"Top", "Topo"},
        {"Bottom", "Inferior"},
        {"Left", "Esquerda"},
        {"Right", "Direita"},

        {"Yes", "Sim"},
        {"No", "Nao"},
        {"Unknown", "Desconhecido"},
        {"Actions", "Acoes"},
        {"Health", "Vida"},
        {"Armor", "Colete"},
        {"Speed", "Velocidade"},
        {"Value", "Valor"},
        {"Key", "Tecla"},
        {"Target NPC", "NPC Alvo"},
        {"Visible Check", "Verificar Visivel"},
        {"Smooth X", "Suavidade X"},
        {"Smooth Y", "Suavidade Y"},
        {"Magic Bullet", "Bala Magica"},
        {"Magic Key", "Tecla Magica"},
        {"Aim Dead", "Mirar Mortos"},
        {"Show NPC", "Mostrar NPC"},
        {"Show Dead", "Mostrar Mortos"},
        {"Show Local", "Mostrar Local"},
        {"RGB Mode", "Modo RGB"},

        {"Highlight Visible", "Destacar Visivel"},
        {"Doors (Lock/Unlock)", "Portas (Trancar/Destrancar)"},
        {"Lock Status Icon", "Icone de Status de Trava"},
        {"God Mode Key", "Tecla do Modo Deus"},
        {"Noclip Key", "Tecla do NoClip"},
        {"Noclip Speed", "Velocidade do NoClip"},

        {"Repair Key", "Tecla de Reparo"},
        {"Rocket Boost Key", "Tecla do Foguete"},
        {"TP Way Key", "Tecla do TP Waypoint"},
        {"Grab Key", "Tecla de Agarrar"},
        {"Reaction Time", "Tempo de Reacao"},
        {"Run Speed", "Velocidade da Corrida"},
        {"Vehicle Boost", "Boost do Veiculo"},
        {"Processor Delay", "Atraso do Processador"},
        {"Hold Distance", "Distancia de Segurar"},
        {"Hold Height", "Altura de Segurar"},
        {"Throw Force", "Forca do Lancamento"},

        {"Fov Color", "Cor do Campo"},
        {"Box Color", "Cor da Caixa"},
        {"Skeleton Color", "Cor do Esqueleto"},
        {"Friend Color", "Cor do Amigo"},
        {"Text Color", "Cor do Texto"},
        {"Snaplines Color", "Cor das Linhas"},
        {"Health Bar Color", "Cor da Barra de Vida"},
        {"Armor Bar Color", "Cor da Barra de Armadura"},
        {"Head Circle Color", "Cor do Circulo na Cabeca"},

        {"Name Color", "Cor do Nome"},
        {"Distance Color", "Cor da Distancia"},
        {"Snap Lines Color", "Cor das Linhas de Mira"},
        {"Locked Color", "Cor Trancado"},
        {"Unlocked Color", "Cor Destrancado"},
        {"Color", "Cor"},
        {"Not connected...", "Nao conectado..."},
        {"Select a player from the list", "Selecione um jogador da lista"},
        {"Select a vehicle from the list", "Selecione um veiculo da lista"},
        {"Server starting...", "Servidor iniciando..."},
        {"Subscription: LIFETIME", "Assinatura: VITALICIA"},
        {"Days Left: %d", "Dias Restantes: %d"},
        {"EXPIRED", "EXPIRADO"},
        {"Stop spectating", "Parar de assistir"},
        {"Stop spectate", "Parar assistir"},
        {"Spectate", "Assistir"},
        {"Remove friend", "Remover Amigo"},
        {"Teleport to player", "Teleportar para Jogador"},
        {"Teleport to vehicle", "Teleportar para Veiculo"},
        {"Pull Player", "Puxar Jogador"},
        {"Pull Vehicle", "Puxar Veiculo"},
        {"Unlock vehicle", "Destrancar Veiculo"},
        {"Copy URL", "Copiar URL"},
        {"Discord", "Discord"},
        {"Release Vehicle", "Soltar Veiculo"},
        {"Throw Vehicle", "Lancar Veiculo"},

        {"Vehicle Grab", "Agarrar Veiculo"},
        {"Smart Trigger", "Gatilho Inteligente"},
        {"URL: %s", "URL: %s"},
        {"Add friend", "Adicionar Amigo"},
        {"LOGIN", "ENTRAR"},
        {"You", "Voce"},
        {"Vehicle", "Veiculo"}
    };

    inline std::string Get(const std::string& text)
    {
        if (!IsPortuguese) return text;

        auto it = Translations.find(text);
        if (it != Translations.end())
            return it->second;

        return text;
    }
}

#define _T(text) Language::Get(text).c_str()
